---
region: us-east-1
iam:
  policy:
    name: ExecRolePolicy
  role:
    name: EXECROLE
lambda:
  name: HugoLambdaGenerate
  zipfile_name: HugoGenerate.zip
  description: An S3-triggered aggregation of static content
  path: lib/
  handler: RunHugo.handler
  runtime: nodejs
  memory_size: 128
  timeout: 60
  mode: event
  test_data: sample.json
  permissions:
    - statement_id: s3_invoke
      action: lambda:invokeFunction
      principal: s3.amazonaws.com
      source_arn: arn:aws:s3:::input.rsb.io
  event_sources:
    - arn: arn:aws:s3:::input.rsb.io
      events:
        - s3:ObjectCreated:*
