---
region: us-east-1
cloudformation:
  template: ../hugo-lambda.cfn
  stack_name: HugoLambdaStack
  exec_role: ExecRole
  invoke_role: InvokeRole
lambda:
  name: HugoLambdaGenerate
  zipfile_name: HugoGenerate.zip
  description: An S3-triggered aggregation of static content
  path: lib/
  handler: RunHugo.handler
  runtime: nodejs
  memory_size: 128
  timeout: 60
  mode: event
  test_data: sample.json
  event_sources:
    - arn: arn:aws:s3:::input.test.rsb.io
      events:
        - s3:ObjectCreated:*
