---
region: us-east-1
cloudformation:
  template: ../hugo-lambda.cfn
  stack_name: HugoSiteStack
  exec_role: ExecRole
  invoke_role: InvokeRole
lambda:
  name: HugoLambdaStaticSync
  zipfile_name: HugoStaticSync.zip
  description: Sync only static content (not template/post content)
  path: lib/
  handler: StaticSync.handler
  runtime: nodejs
  memory_size: 128
  timeout: 60
  mode: event
  test_data: sample.json
  event_sources:
    - arn: arn:aws:s3:::input.rsb.io
      events:
        - s3:ObjectCreated:*
