---
region: us-east-1
cloudformation:
  template: ../hugo-lambda.cfn
  stack_name: HugoLambdaStack
  exec_role: ExecRole
  invoke_role: InvokeRole
lambda:
  name: HugoLambdaGenerate
  zipfile_name: HugoGenerate.zip
  description: An S3-triggered rebuild of a static site.
  path: lib/
  handler: RunHugo.handler
  runtime: nodejs
  memory_size: 128
  timeout: 5
  mode: event
  test_data: input.json
  event_sources:
    - arn: arn:aws:s3:::tar.rsb.io
  s3_events:
    - s3:ObjectCreated:*
