---
  AWSTemplateFormatVersion: "2010-09-09"
  Parameters:
    BucketName:
      Description: "Name of S3 bucket that serves the web site"
      Type: "String"
  Resources:
    ExecRole:
      Type: "AWS::IAM::Role"
      Properties:
        AssumeRolePolicyDocument:
          Statement:
            - Effect: "Allow"
              Principal:
                Service: ["lambda.amazonaws.com", "s3.amazonaws.com"]
              Action: ["sts:AssumeRole"]
          Version: "2012-10-17"
    ExecRolePolicies:
      Type: "AWS::IAM::Policy"
      Properties:
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "s3:HeadObject"
                - "s3:ListAllMyBuckets"
                - "s3:GetBucketLocation"
              Resource: ["arn:aws:s3:::*"]
            - Effect: "Allow"
              Action: "s3:*"
              Resource:
                - Fn::Join:
                    - ""
                    - ["arn:aws:s3:::", {"Ref": "BucketName"}]
                - Fn::Join:
                    - ""
                    - ["arn:aws:s3:::", {"Ref": "BucketName"}, "/*"]
            - Effect: "Allow"
              Action: ["logs:*"]
              Resource: "arn:aws:logs:*:*:*"
            - Effect: "Allow"
              Action: ["cloudfront:*"]
              Resource: "*"
            - Effect: "Allow"
              Action:
                - "iam:GetServerCertificate"
                - "iam:ListServerCertificates"
                - "iam:UploadServerCertificate"
                - "iam:UpdateServerCertificate"
                - "iam:DeleteServerCertificate"
              Resource: "*"
        Roles:
          - {"Ref": "ExecRole"}
        PolicyName: "ExecRolePolicy"
    LetsEncryptRegistrator:
    # zip creation: launch ami-1ecae776
    # yum install -y gcc libffi libffi-devel openssl-devel python-virtualenv
    # virtualenv -p /usr/bin/python dep_venv
    # source dep_venv/bin/activate
    # pip install letsencrypt letsencrypt-s3front
    # tar czf deps.tgz dep_venv/lib/python2.7/site-packages
      Type: "AWS::Lambda::Function"
      Properties:
        Handler: lambda_function.lambda_handler
        Role: {"Fn::GetAtt": [ExecRole, Arn]}
        Runtime: python2.7
        Timeout: 120
        Code:
          S3Bucket: "demos.serverlesscode.com"
          S3Key: "letsencrypt-function.zip"
  Outputs:
    LetsEncryptCustomFunction:
      Description: "Function to register CloudFront sites with Letsencrypt"
      Value: {"Fn::GetAtt": [LetsEncryptRegistrator, "Arn"]}
